pull_request_template.md

fix: pull_request_template edit emoji

---

next.config.js
package.json
pages/index.tsx
pages/main.tsx
styles/globals.css
styles/main.ts
yarn.lock

- ​메인 페이지 레이아웃
<br/>
​
- ​배경 색, 아이콘 찾아보기
<br/>
​
- ​
<br/>

markup: mainpage

---

pages/main.tsx
pages/story.tsx
styles/main.ts
styles/story.ts

- ​story Page 개발
<br/>
​
- ​story page 레이아웃
<br/>
​
- ​SSR / CRS 구별 어떻게 해야 될까
- 밑에 공백은 footer가 들어올 예정
- 여기는 header를 없애고 싶은데 어떻게 해야할지
<br/>

feat: story page

---

pages/story/styled.ts

- ​fontsize 고쳤슴다
<br/>
​
- ​
<br/>
​
- ​
<br/>

fix: fontsize

---

package.json
pages/_app.tsx
pages/main/index.tsx
pages/main/spinner.scss
pages/main/styled.ts
yarn.lock

- 스토리 버튼을 눌렀을 때 진행되는 애니메이션과 story 페이지로 이동하는 인스타그램을 벤치마킹해서 구현
- 개별적으로는 적용하지 못했고 일단 레이아웃 참고용으로 제작
- scss를 부득이하게 사용 style components로 바꿀 예정
<br/>
​
- ​스토리 버튼 레이아웃 및 애니메이션 & push router (/story)​
<br/>
​
- ​sass를 설치해서 yarn install 한번 때리셔야합니다
- style components로 바꾸면 명세서에서 지우도록 하겠슴다
<br/>

feat: story button animation

---

components/atoms/DirectInHeader.tsx
components/atoms/DirectPartner.tsx
components/input/DirectMessage.tsx
components/input/DirectSearchBar.tsx
components/list/DmAccountsList.tsx
components/list/DmContentsList.tsx
pages/direct/in/index.tsx
pages/direct/index.tsx
pages/direct/new/index.tsx
pages/direct/new/styled.ts

- ​다이렉트 메세지 페이지 레이아웃 구성
<br/>
​
- ​다이렉트 메세지 페이지 레이아웃 마크업
<br/>
​
- 디렉토리 구조입니다 참고하세요 ;)
```
- direct (전체 dm 목록)
- - in (대화중인 dm)
- - new (새로운 dm 보내기)
```
<br/>

markup: direct-page layout

---

components/atoms/DirectHeader.tsx
pages/notifications/index.tsx
pages/notifications/styled.ts

- ​알림 페이지 레이아웃 구성
<br/>
​
- ​알림 페이지 레이아웃 마크업
<br/>
​
- ​
<br/>

markup: notifications page layout

---

components/styledFooter.ts
pages/reels/index.tsx
pages/reels/styled.ts

- ​릴스 페이지 전환 애니메이션 구현
<br/>
​
- ​touchesEvent로 touchStart와 touchEnd를 감지해서 
- start가 end보다 크면 아래로 스크롤 
- start가 end보다 작으면 위로 스크롤
- useRef로 containerRef를 지정해서 scrollTo로 count값이 바뀔때마다 useEffect로 scrollTo메서드가 실행되도록 지정
<br/>
​
- ​별거 아닌데 추석 내내 이거만 했네
<br/>

feat: reels transition

---

db.json
email.json
package.json
pages/signup/auth.tsx
pages/signup/index.tsx
pages/signup/styled.ts

- ​signupPage layout 생성
- 이메일 shortcut 버튼 생성
- 중복검사 json-server로 get, post
<br/>
​
- ​proxy: http:localhost:3000 생성
<br/>
​
- ​proxy일단 설정해놨어요!
<br/>

feat: signupPage layout & 중복검사

---

email.json
pages/signup/details/index.tsx
pages/signup/details/styled.ts
pages/story/index.tsx

- ​닉네임과 패스워드를 설정하는 페이지를 작성
- 닉네임 유효성 및 패스워드 유효성 설정
- 닉네임 중복 버튼을 삭제하고 input이 blur되었을 때 바로 get요청으로 닉네임 중복상태 확인
<br/>
​
- blur with get method​
- 닉네임 및 패스워드 유효성 검사 구현
<br/>
​
- ​input type="password"일 시 제주고딕 폰트가 적용이 안돼서 빈 문자열로 보이는 버그가 있어서 일단 해당 input은 font-family:'Aria'로 지정
- styled components에서 placeholder만 어떻게 설정하지?!?!!
<br/>

feat: signup > details Page

---

components/Footer.tsx
components/Header.tsx
components/atoms/DirectHeader.tsx
components/atoms/DirectInHeader.tsx
components/atoms/Icons.tsx
components/atoms/post/PostContent.tsx
components/atoms/post/styled.ts
components/input/DirectSearchBar.tsx
components/list/DmAccountsList.tsx
components/list/DmSearchList.tsx
components/list/ResultsList.tsx
kj.json
package.json
pages/direct/index.tsx
pages/direct/new/index.tsx
pages/explore/index.tsx
pages/notifications/index.tsx
pages/post/[id].tsx
styled/direct_new.ts
styled/explore.ts

- 자질 구레하게 컴포넌트와 기능 수정하고 생성하고
- ​새로운 채팅방 만드는 기능 위주로 진행하였습니다아
<br/>​
- ​여기저기 자주 사용하는 뒤로가기 두 종료의 아이콘 컴포넌트로 생성
- header, footer 아이콘 사이즈 조정
- direct-new-[age 에서 계정 검색 테스트
- 계정 검색 후 선택된 계정 input searchBar에 담기는 기능 진행중 !
- 이미지 컴포넌트 사용해서 렌더링하는데 값은 불러와지지만 렌더링이 안되는 중인데 왜그러는지 모르게쒀요ㅠㅠ
<br/>​
- ​다들 감기 조심하세여
- 거북목 조심하세여
<br/>

Feat: direct-new-page 새로운 채팅방 만들기

---

json-server-data/account.json
json-server-data/email.json
pages/my/settings/account/index.tsx
pages/my/settings/job/index.tsx
pages/signup/details/index.tsx
pages/signup/job/index.tsx

- ​닉네임 post 후 생성된 id값을 session으로 추적하여 job을 patch할 수 있고 후에 수정도 가능
<br/>
​
- ​patch / post 메서드
<br/>
​
- ​json-server-data폴더로 이동후에
-  ``json-server --watch account.js --port 5000`` 으로 server켜서 테스트 가능! signup페이지에서 회원가입절차대로 해야합니당
<br/>

feat: 계정 설정  post / patch

---

components/Footer.tsx
components/styled/my_recommend.ts
data.json
pages/my/index.tsx
pages/my/recommend/index.tsx
pages/user/[id].tsx

- ​친구추천페이지에서 해당 유저의 피드로 들어갈때 이전 페이지에서 쿼리 파라미터로 user id, user name을 받아와 피드에 동적으로 구현(사실 props를 생각 못해서 고생함)
- 해당 유저 팔로, 언팔 온클릭 기능 구현
<br/>
​
- ​
<br/>
​
- ​하.......힘드네요...... 이전 프로젝트에서 내가 쉬운 것만 한듯...............촉박한 너낌
- 나는 왜케 props 같은 데이터를 받아오는게 어려울까(안해서)
- 이제 crud는 또 어떻게 하지?ㅠ
<br/>

Feat: 친구추천 페이지, 팔로우

---

pages/_app.tsx

- ​_app.tsx 파일에 scss import 문 삭제
<br/>
​
- ​찾을 수 없는 모듈이라고 에러가 발생하여 삭제하였습니다
<br/>
​
- ​
<br/>

delete: scss import statement

---

pages/story/index.tsx

- ​전에는 이미지를 넘기면 전에 이미지가 갑자기 뒤바뀌어서 UX에 악영향을 미쳤었는데 고걸 해결했습니다.
- 문제는, 이미지를 배열로 관리하고 index를 상태로 관리해서 클릭할때마다 index가 증감하여 이미지 배열에서 이미지를 불러오는 방식이었는데 index를 로컬 상태관리로 관리하는 바람에 전체 이미지가 index의 영향을 받아서 이미지가 넘어갈때 전에 이미지도 바뀌게 되는것이었습니다.
- 해결방법은 데이터를 불러온다음에 각 컨텐츠의 이미지 길이를 상태로 새로 관리하는 것입니다. `Array(data.length)`로 data의 길이만큼 Array를 새로 만들고 `fill(0)`으로 값을 입력한다음에 클릭할 시 해당 index에 맞는 값만 증감하고 해당 index의 값만 불러들이는 방식으로 사용했습니당
<br/>
-전 
-후
​
- ​상태관리 추가를 통한 디테일 퍼포먼스 증가 및 UX증가
<br/>
​
- ​아직 그래도 뒤 컨텐츠가 사진이 바뀔때 슬쩍슬쩍 보이는것이 거슬리네요 ㅠㅠ 계속해서 디테일 추가중
<br/>

fix: 이미지 넘어갈 때 전 이미지 고정하기

---

.env
next.config.js
pages/signin/index.tsx

- ​서버를 배포함에 따라 환경변수에 서버 주소를 담아서 앞으로 있을 axios instance나 여러가지 요청을 좀 더 보안적이고 간편하게 할 수 있게 되었습니다
<br/>
​
- ​서버 주소 환경 변수 저장
<br/>
​
- ​
<br/>

fix: 서버 주소 환경변수 설정

---

components/Post/Contents.tsx
components/Post/Top.tsx
components/atoms/Header.tsx
components/atoms/Modal.tsx
components/styled/my.ts
pages/main/index.tsx
pages/my/index.tsx
pages/signin/index.tsx
pages/signup/auth/index.tsx
pages/signup/emailState.ts
services/postInfo/getMyPostAll.ts
src/redux/Posts/store.ts
src/redux/Posts/userSlice.ts

- ​typeError 보이는 건 해결했는데 또 있으면 알려주세요
- userSlice.reducer, registerSlice.reducer 컴바인 리듀서에 포함시켰습니다!
- 임의로 emailState => registerSlice.reducer로 수정했는데 정호님께서 편하신대로 수정하셔도됩니다!
<br/>
​
- ​전반적인 type error 해결
- userSlice.reducer가 store(RootState)에 담겨있지 않았음
- emailState 변수 명이 헷갈려서 임의로 수정 진행
<br/>
​
- ​오늘 안으로 리덕스랑 친해지긴 어렵겠네요
<br/>

Fix: userSlice.reducer 오류 해결 후 전반적인 typeError 수정

---

pages/signup/auth/index.tsx
pages/signup/emailState.ts
pages/signup/job/index.tsx

- ​경진님과 createSlice 변수명이 같아서 오류가 생겼었는데 저는 register로 변경해서 고쳤습니다
- 코드가 삭제돼서 다시 수정했습니다 이제 회원가입 하고 로그인 해보면 잘됩니당
<br/>
​
- ​Redux 전역상태 이름 변경 및 버그 수정
<br/>
​
- ​챕터를 넘어갈때마다 로딩 애니메이션이나 모달을 만들어야겠어요 진행되는 여부를 알 수가 없는데 빠른 시일내에 올려보도록 하겠습니다
- 일단 연동먼저 다 해볼게요!
<br/>

fix: Redux 전역상태 이름 변경 및 버그 수정

---

components/styled/signin.ts
components/styled/signup_details.ts
pages/signin/index.tsx
pages/signup/auth/index.tsx
pages/signup/details/index.tsx
pages/signup/job/index.tsx

- ​제주고딕은 password의 ⦁기호를 읽지 못해서 투명하게 나오기 때문에 placeholder은 제주고딕, input의 값은 기본 흔한 폰트로 적용해야 했슴
- 개발 당시에는 아무리 찾아도 없었는데 오늘 어찌저찌 하다보니 해결했음
- 해결방법은 `&::palceholder{}`로 styled-components에서 바로 attrs을 커스터마이징 할 수 있었슴 
<br/>
​
- ​placeholder font 바꾸기
<br/>
​
- ​덤으로 유리님 페이지 singin페이지도 수정해놓음!
- 덤으로 회원가입 완료 시 signin페이지로 이동해서 로그인 유도하게 했음!
<br/>

fix: placeholder font/color

---

components/atoms/EditModal.tsx
components/styled/my_feeds_edit.ts

- ​파일 수정이 있었습니다
<br/>​
- ​
<br/>​
- ​
<br/>

Edit: 파일 수정

---

components/Header.tsx
components/styled/main_boardwrite_details.ts
pages/create/details/index.tsx
pages/create/story/index.tsx
pages/signup/job/index.tsx

- 로컬이미지로 미리보기를 구현
- 공유하기 버튼을 누르면 파이어베이스에 해당 이미지 업로드
- 업로드 된 이미지 주소를 서버에 전달
- 모두 비동기로 동작
<br/>
​
- ​create/details 이미지 업로드 및 파이어베이스연동
<br/>
​
- ​리사이징 기능(이미지 용량 줄이기)까지 완료한 다음에 리팩토링 해볼게요!
<br/>

refactor: create/details 이미지 업로드 및 파이어베이스연동

---

components/Chat/AccountList.tsx
components/Post/Contents.tsx
components/atoms/Button.tsx
components/atoms/Item.tsx
components/atoms/Modal.tsx
components/input/SearchBar.tsx
components/styled/my.ts
components/styled/notifications.ts
pages/direct/new/index.tsx
pages/my/index.tsx
pages/notifications/index.tsx
pages/post/comment/liked_by/[commentId].tsx
pages/post/liked_by/[postId].tsx
pages/user/[id].tsx
services/chatInfo/postChatRoom.ts

- ​마이페이지 네비게이션바에서 탭 간에 api 호출이 잘 안되는 오류 발생
- 검색페이지에서 계정 검색 후 클릭시 라우터로 해당 계정 페이지로 이동
- 알림페이지 sse로 멘션 오는 것 재확인 완료
<br/>
​
- ​특정 키워드에 맞게 이벤트 핸들링을 부여해서 클릭 이벤트에 대한 동작을 구분해서 처리
- 라우터쿼리로 멤버 아이디 가져와서 유저페이지에 필요한 호출 api에 연결
<br/>
​
- ​
<br/>

fix: 마이페이지 네비게이션바 오류 해결, 검색페이지 & 알림페이지  api 연동 오류 재확인

---

pages/create/details/[id].tsx
pages/create/details/index.tsx

- ​백엔드에서 Firebase의 이미지를 지우기 위해 Post 요청 시 image 파일명 추가해서 요청
<br/>
​
- ​image 파일명 업로드
<br/>
​
- ​리사이징 왜 안되죠...? ㅈ밥이 아니네요...
<br/>

fix: image 파일명 업로드

---

pages/signup/job/index.tsx

- ​경진님이 발견한 직업이 안넘어가는 버그 수정!
- job을 redux로 저장 -> Redux로 저장된 개인정보 불러오기 이런식으로 했었는데
- 굳이 직업은 redux로 저장해서 한꺼번에 불러올  필요가 있나 바로 여기서 보내면 되겠다 해서 수정했습니다
- axiosInstance로 리팩토링완료!
<br/>
​
​
- ​
<br/>

fix: job 요청 보내기

---

components/Header.tsx
components/styled/header.ts
components/styled/signin.ts
pages/create/details/handleResizeImage.ts
pages/create/story/index.tsx
pages/signup/job/index.tsx
pages/story/getStorydata.ts
pages/story/index.tsx

- ​story도 이제 리사이징하여 1/10 정도로 용량줄임
- 그동안 안되었던게 story는 텍스트도 넣어야 하기 때문에 텍스트 넣은 상태를 캡처해서 이미지로 보내는데
- 캡처된 이미지가 blob형태라 blob은 file이 아니므로 file리사이징 불가
- blob을 file로 바꾼후에 리사이징
<br/>
​
- ​blob을 file로 바꾼후에 리사이징
- 페이지 리팩토링
<br/>
​

refactor: story 이미지 리사이징 & 리팩토링

---

components/atoms/Item.tsx
pages/my/[id]/comments/index.tsx
pages/my/[id]/comments/modal.tsx
pages/my/[id]/comments/useLongPress.tsx
pages/my/feeds/[id]/comments/modal.tsx
pages/my/index.tsx
pages/my/recommend/index.tsx
services/userInfo/getUserRecommed.ts

- ​​마이페이지 -> 추천친구 api연결
- 답글달기 시 상대방의 이름 태깅 기능 추가
<br/>
​
- ​
<br/>
​
- ​안녕하세요
- 정호님거 머지받고 다시 올림
<br/>

Feat. 추천 친구 API 연동, 댓글 태깅 기능

---

components/styled/create_details.ts
pages/create/details/index.tsx
pages/signin/index.tsx

- ​이미지를 여러장 보내기 위해 UI를 개편했습니다!
- 인스타는 모달을 띄워서 여러개의 이미지를 다룰 수 있게 했더라고요
- 그래서 비슷하게 만들어봤습니다
- 드래그 & 드롭은 아직 못함 ㅠㅠ
- post요청은 아직 손을 못대서 현재 미리보기와 관계없이 맨 처음 올린 이미지가 post됩니다
<br/>
​
- ​이미지 여러장 올리기 모달 구현 및 트랜지션 구현
<br/>
​
<br>
<br>
<br>
<br>
<br/>

feat: Images Modal & Add Images & Delete Images

---

pages/create/details/index.tsx
pages/signin/index.tsx

- ​이미지 업로드시에 5장 이하로 다중 선택해서 업로드 가능합니다.
- 미리보기 이미지 클릭 시 모달이 띄워집니다.
- 띄워진 모달은 다중 선택한 이미지가 미리보기로 보여집니다.
<br/>
​
- ​다중 이미지 업로드 및 미리보기 구현
<br/>
​
- ​찐 업로드는 아직 한장밖에 안됩니다 ㅠㅠㅠ
<br/>

refactor: 다중 이미지 업로드 및 미리보기 구현

---

components/Post/Top.tsx
components/atoms/Modal.tsx
pages/explore/post/[id].tsx
pages/my/index.tsx
pages/post/[id].tsx
pages/user/[id].tsx

- handlePostUpdate 연관성 데이터의 타입 오류
<br/>
​
- ​
<br/>
​
- ​
<br/>

fix: 게시글 수정하기 handlePostUpdate 함수 타입 오류

---

pages/notifications/index.tsx

- ​
<br/>
​
- ​
<br/>
​
- ​
<br/>

fix: 알림페이지 타입 오류

---

components/atoms/Comment.tsx

- ​Input type인데 왜 Textarea type이라 했을꼬 ..ㅎㅎ
<br/>
​
- ​
<br/>
​
- ​
<br/>

Fix: CommentItem 타입 에러 수정

---

components/Footer.tsx
components/Header.tsx
components/Post/Top.tsx
components/atoms/Button.tsx
components/atoms/Icon.tsx
components/atoms/Item.tsx
components/styled/header.ts
hook/connectSSE.ts
hook/connectWebSocket.tsx
pages/direct/in/[roomId].tsx
pages/notifications/index.tsx
styles/globals.css

- ​배포된 서버 url이 변경되어 웹소켓 url 수정하였습니다
- sse 중복으로 연결할 때 오류가 있었는데 확인해서 수정했습니다 별다른 오류는 아니고 그냥 타입오류였음
- 웹소켓 핸들러 사용한는 컴포넌트에서 중복되는 코드 모듈화해서 파일 생성했음
- 버튼 기본 css 초기화하는 코드 추가
- 헤더 컴포넌트 width: 100%로 수정
<br/>
​
- ​
<br/>
​
- ​
<br/>

fix: 웹소켓 연결 url 수정 & sse와 websocket 중복 코드 모듈화
